name: Automatic Merge Pull Request
on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          method: squash