name: automerge
on:
  pull_request_target:
    types: [opened, edited]

jobs:
  automerge:  # https://github.com/marketplace/actions/merge-pull-requests-automerge-action
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_DELETE_BRANCH: true