name: Merge Bot

on:
  label:
    types: [created, deleted]

jobs:
  merge:
    needs: label
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        reviewers: false
        labels: ready
        checks_enabled: false
        method: squash
        delete_source_branch: false