name: Automatic Merge
on:
  pull_request_target:
    types: [labeled, edited]

permissions: write-all

jobs:
  Merger:  # https://github.com/marketplace/actions/pr-merge-bot
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        reviewers: false
        blocking_labels: do not automerge
        checks_enabled: false
        method: squash
        delete_source_branch: true