name: "Pull Request Labeler"
on:
  pull_request:

jobs:
  triage:  # https://github.com/marketplace/actions/labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  merge:  # https://github.com/marketplace/actions/pr-merge-bot
    needs: triage
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: false
        reviewers: false
        labels: "ready"
        blocking_labels: "do not merge"
        checks_enabled: false
        method: squash
        delete_source_branch: true