name: Automatic Label and Merge
on:
  pull_request_target:
    types: [opened, edited]

jobs:
  Labeler:  # https://github.com/marketplace/actions/labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  Merger:  # https://github.com/marketplace/actions/pr-merge-bot
    needs: Labeler
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: false
        blocking_labels: do not automerge
        checks_enabled: true
        method: squash
        delete_source_branch: true